### ISSUE TITLE
General Complexity

### ISSUE THREAD

**Issue by mattdesl** [ngokevin/aframe-component-boilerplate#4]
IMHO the current boilerplate is overly complex and adds a lot of barriers to entry; limiting the number of components that will be created by the open source community.

Here are my concerns:
- Why is browserify _and_ webpack used?
- What is the purpose of the `browser.js` build and how does it differ from dist, or index?
- The `ghpages` stuff seems superfluous to me, some components won't have a demo, and others might use [their own scripts](https://github.com/mattdesl/ghpages) to manage publishing.
- The `dev` step seems limited; I still need to run my own server to actually test and develop the `examples/`?
- The test hooks and init configs are a little overwhelming (I am only familiar with tape, which tends to [be much simpler](https://github.com/Jam3/ray-3d/blob/master/test.js)).
- Are all components expected to follow this set of guidelines, or is it going to be more lenient?

With so much boilerplate/tools/config/etc in this repo, there will inevitably be a lot of fixes and changes in this repo over time (like https://github.com/ngokevin/aframe-component-boilerplate/pull/3), and community-driven components will lag behind.

**Comment by ngokevin** [comment]
- I wasn't concerned with using both as long as they were abstracted away with NPM scripts. I liked `watchify` for developing examples and `webpack` to produce browser builds with less overhead and do uglifying with a single flag. If it's a concern, I can switch to fully Webpack.
- `browser.js` is used to generate the `dist` files. It `require`s the source files.
- As a boilerplate, people are free to use it or not use it. But it provides an easy way for people to share their component demos (write HTML files, then `npm run ghpages`). Not sure why people would want to switch out the scripts to achieve the same thing either, but they're free to.
- Hm, I was just opening the files in the browser without a server. I can see limitations of that. Do you suggest `watchify-server`?
- People are free to switch out the test suite if they want something else. Karma + Mocha is pretty popular, and it mirrors the setup we're using for A-Frame. We have about 200 tests on A-Frame running off of it and it brings over a lot of useful things such that people can start writing tests without having to worry about A-Frame setup/teardown or getting bit by not waiting for entities to load.
- It's just a boilerplate, so we're not enforcing the use of this. It's just here to help people get started if they want to use it. So yeah I'd say it's extremely lenient.

**Comment by ngokevin** [comment]
And thanks for raising these concerns :)

**Comment by cvan** [comment]
@mattdesl: re: @ngokevin's response, which changes would you like to see in this/an A-Frame component boilerplate?

**Comment by ngokevin** [comment]
I made steps to make this less complex:
- Script to automatically rename and trim things.
- Removal of the browser.js step now that the NPM module will also just call AFRAME.registerComponent.
- `dev` step uses budo now.
- Same as before, Github pages is just one command `npm run ghpages`.
