### ISSUE TITLE
Package.json Version Concerns

### ISSUE THREAD

**Issue by mattdesl** [ngokevin/aframe-component-boilerplate#5]
In package.json:

``` js
  "version": "0.1.0",
```

Boilerplate version should probably start at `1.0.0` to avoid common problems with the [magic zero](https://github.com/mojombo/semver/issues/221). Most users are unaware of the subtle differences and will leave it at whatever version is set in the boilerplate.

``` js
    "aframe-core": "*",
```

It might be good to avoid wildcards and just try to keep the boilerplate up to date with whatever is the latest version of `aframe-core`. Otherwise community driven components will quickly start running into version woes with wildcard dependencies.

**Comment by ngokevin** [comment]
Addressed, thanks!
